services:

  db_mysql:
    image: mysql:8.0
    container_name: mysql_hospital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"


  # Microservicio paciente
  paciente:
    build:
      context: ./01-paciente
      dockerfile: Dockerfile
    container_name: 01-paciente
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_paciente
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  # Microservicio medico
  medico:
    build:
      context: ./02-medico
      dockerfile: Dockerfile
    container_name: 02-medico
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_medico
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio especialidades
  especialidades:
    build:
      context: ./03-especialidades
      dockerfile: Dockerfile
    container_name: 03-especialidades
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_especialidades
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

volumes:
  mysql_data: