services:

  db_mysql:
    image: mysql:8
    container_name: mysql_hospital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"


  # Microservicio paciente
  paciente:
    build:
      context: ./01-paciente
      dockerfile: Dockerfile
    container_name: 01-paciente
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_paciente
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  # Microservicio medico
  medico:
    build:
      context: ./02-medico
      dockerfile: Dockerfile
    container_name: 02-medico
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_medico
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio especialidades
  especialidades:
    build:
      context: ./03-especialidades
      dockerfile: Dockerfile
    container_name: 03-especialidades
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_especialidades
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio agenda
  agenda:
    build:
      context: ./04-agenda
      dockerfile: Dockerfile
    container_name: 04-agenda
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_agenda
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio reservas
  reservas:
    build:
      context: ./05-reservas
      dockerfile: Dockerfile
    container_name: 05-reservas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_reservas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio consultas
  consultas:
    build:
      context: ./06-consultas
      dockerfile: Dockerfile
    container_name: 06-consultas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_consultas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio pagos
  pagos:
    build:
      context: ./07-pagos
      dockerfile: Dockerfile
    container_name: 07-pagos
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pagos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio recetas
  recetas:
    build:
      context: ./08-recetas
      dockerfile: Dockerfile
    container_name: 08-recetas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_recetas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio historial clinico
  historialclinico:
    build:
      context: ./09-historialclinico
      dockerfile: Dockerfile
    container_name: 09-historialclinico
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_historialclinico
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio notificaciones
  notificaciones:
    build:
      context: ./10-notificaciones
      dockerfile: Dockerfile
    container_name: 10-notificaciones
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_notificaciones
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

volumes:
  mysql_data: