CREATE TABLE pagos (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
id_paciente INTEGER NOT NULL,
monto DOUBLE NOT NULL,
fecha_pago DATETIME NOT NULL,
medio_pago VARCHAR(50) NOT NULL,
estado_pago VARCHAR(50) NOT NULL,
activo BOOLEAN NOT NULL
);